<?php declare(strict_types=1);

use Yireo\NextGenImages\Block\Picture;
use Yireo\NextGenImages\Block\Picture;

/** @version 0.5.15 */
/** @var Picture $block */
/** @var Escaper $escaper */

$width = ($block->getWidth()) ? ' width="'.$block->getWidth().'"' : '';
$height = ($block->getHeight()) ? ' height="'.$block->getHeight().'"' : '';
$class = ($block->getClass()) ? ' class="'.$block->getClass().'"' : '';
$lazyLoading = ($block->getLazyLoading()) ? ' loading="lazy" ' : '';
$originalTag = trim($block->getOriginalTag());
$originalTag = preg_replace('/(\/?)>$/', $lazyLoading.'\1>', $originalTag);
$originalImage = $block->getOriginalImage();
$originalImageType = $block->getOriginalImageType();
$srcAttribute = $block->getSrcAttribute() ?? 'src';
$srcSetAttribute = $srcAttribute.'set'; 
?>
<picture<?= /* @noEscape */ $class ?>>
    <?php if ($block->getDebug()): ?>
        <!-- <?= $escaper->escapeHtml($block->getOriginalAttributesAsString()) ?> -->
    <?php endif; ?>
  
    <?php foreach ($block->getImages() as $image): ?>
        <source 
            type="<?= /* @noEscape */ $image->getMimeType() ?>" 
            <?= /* @noEscape */ $srcSetAttribute ?>="<?= /* @noEscape */ $image->getSrcSet() ?: $image->getUrl() ?>" 
            <?= /* @noEscape */ $block->getSourceAttributesAsString() ?>
        >
    <?php endforeach; ?>
    <?= /* @noEscape */ $originalTag ?>
</picture>
