<?php

declare(strict_types=1);

/** @var $block \Yireo\NextGenImages\Block\Picture */

$width = ($block->getWidth()) ? ' width="' . $block->getWidth() . '"' : '';
$height = ($block->getHeight()) ? ' height="' . $block->getHeight() . '"' : '';
$class = ($block->getClass()) ? ' class="' . $block->getClass() . '"' : '';
$lazyLoading = ($block->getLazyLoading()) ? ' loading="lazy" ' : '';

$originalTag = trim($block->getOriginalTag());
$originalTag = preg_replace('/(\/?)>$/', $lazyLoading . '\1>', $originalTag);

$originalImage = $block->getOriginalImage();
$originalImageType = $block->getOriginalImageType();
?>
<?php if ($block->getDebug()): ?>
    <!-- <?= /* @noEscape */
    $block->getOriginalTag() ?> -->
<?php endif; ?>

<picture<?= /* @noEscape */
$class ?>>
    <?php foreach ($block->getSourceImages() as $sourceImage) : ?>
        <source type="<?= /* @noEscape */
        $sourceImage->getMimeType() ?>" srcset="<?= /* @noEscape */
        $sourceImage->getUrl() ?>">
    <?php endforeach; ?>
    <source type="<?= /* @noEscape */
    $originalImageType ?>" srcset="<?= /* @noEscape */
    $originalImage ?>">
    <?= /* @noEscape */
    $originalTag ?>
</picture>
