<?php
/**
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$script = <<<JS
    'use strict'
    document.addEventListener('alpine:init', () => {
        Alpine.data('initGallery', () => {
            const galleryInitData = initGallery();
            document.dispatchEvent(new CustomEvent('gallery-init', {detail: galleryInitData}));
            return galleryInitData;
        });
    });
JS;

echo $secureRenderer->renderTag('script', [], $script, false);
