<?php
declare(strict_types=1);

use Yireo\NextGenImages\Block\Adminhtml\System\Config\Gd;

/** @version 0.5.15 */
/** @var $block Gd */
?>
<?php if ($block->hasGdSupport()): ?>
    <div class="message message-success">
    <?= /* @noEscape */ __('WebP is supported by GD') ?>
    </div><?php else: ?>
    <div class="message message-warning">
    <?= /* @noEscape */ __('WebP is not supported by GD') ?>
    </div>
<?php endif; ?>
