<?php
declare(strict_types=1);

use Yireo\NextGenImages\Block\Adminhtml\System\Config\ModuleVersion;

/** @version 0.5.15 */
/** @var $block ModuleVersion */
?>
<?= /* @noEscape */ $block->getModuleVersion() ?>
<?php if ($block->hasHyvaYireoNextGenImages()): ?>
    <div class="message message-warning">
        <?= /* @noEscape */ __('Please remove Hyva_YireoNextGenImages as soon as possible') ?>
    </div>
<?php endif; ?>
