name: ExtDN PHPStan
on: [push, pull_request]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: docker://extdn/magento-phpstan-action:dev
        with:
          composer_name: ${{ secrets.COMPOSER_NAME }}
          composer_version: 2
          phpstan_level: 2
          magento_pre_install_script: .github/workflows/extdn-phpstan-tests-pre-install-m244.sh
